apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backenddeploy
  template:
    metadata:
      labels:
        app: backenddeploy
    spec:
      containers:
      - name: new-my-container
        image: madhut26/madhu-backend
        ports:
        - containerPort: 8080

