apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontenddeploy
  template:
    metadata:
      labels:
        app: frontenddeploy
    spec:
      containers:
      - name: new-my-container
        image: madhut26/madhu-frontend
        ports:
        - containerPort: 80
